// examples/solid/src/App.tsx
import { GistUI, type GistUIAction } from "@gistui/solid";
import { createSignal, For, onCleanup, Show } from "solid-js";
import { MyCard } from "./MyCard";
import { samples } from "./samples";

export function App() {
  const [pick, setPick] = createSignal<keyof typeof samples>("dashboard");
  const [source, setSource] = createSignal(samples.dashboard);
  const [streaming, setStreaming] = createSignal(false);
  const [ownCard, setOwnCard] = createSignal(false);
  const [actions, setActions] = createSignal<GistUIAction[]>([]);
  let timer: ReturnType<typeof setInterval> | undefined;

  // Replays the program in small chunks, the way a model streams it.
  const stream = () => {
    clearInterval(timer);
    const full = samples[pick()];
    let at = 0;
    setSource("");
    setStreaming(true);
    timer = setInterval(() => {
      at = Math.min(full.length, at + 24);
      setSource(full.slice(0, at));
      if (at === full.length) {
        clearInterval(timer);
        setStreaming(false);
      }
    }, 16);
  };
  onCleanup(() => clearInterval(timer));

  return (
    <main style={{ "max-width": "1100px", margin: "0 auto", padding: "16px", display: "grid", gap: "16px", "font-family": "system-ui, sans-serif" }}>
      <header style={{ display: "flex", gap: "12px", "align-items": "center", "flex-wrap": "wrap" }}>
        <strong>GistUI + Solid</strong>
        <select
          value={pick()}
          onChange={(e) => {
            setPick(e.currentTarget.value as keyof typeof samples);
            stream();
          }}
        >
          <option value="dashboard">Dashboard</option>
          <option value="form">Form</option>
        </select>
        <button type="button" onClick={stream}>
          Stream again
        </button>
        <label>
          <input type="checkbox" checked={ownCard()} onChange={(e) => setOwnCard(e.currentTarget.checked)} /> Use my Card
        </label>
      </header>
      <GistUI source={source()} streaming={streaming()} components={ownCard() ? { Card: MyCard } : undefined} onAction={(a) => setActions((xs) => [a, ...xs])} />
      <Show when={actions().length}>
        <pre style={{ "font-size": "12px", background: "#f4f4f5", padding: "12px", "border-radius": "8px", overflow: "auto" }}>
          <For each={actions()}>{(a) => `${JSON.stringify(a)}\n`}</For>
        </pre>
      </Show>
    </main>
  );
}

// examples/react-shadcn/src/App.tsx
import { GistUI, type GistUIAction } from "@gistui/react";
import { ui } from "@gistui/react/ui";
import { useEffect, useRef, useState } from "react";
import { shadcnTokens, shadcnUI } from "./gistui-shadcn";
import { PROGRAM } from "./program";

export function App() {
  const [shadcn, setShadcn] = useState(true);
  const [source, setSource] = useState(PROGRAM);
  const [streaming, setStreaming] = useState(false);
  const [actions, setActions] = useState<GistUIAction[]>([]);
  const timer = useRef<ReturnType<typeof setInterval>>(undefined);

  // Replays the program in small chunks, the way a model streams it.
  const stream = () => {
    clearInterval(timer.current);
    let at = 0;
    setSource("");
    setStreaming(true);
    timer.current = setInterval(() => {
      at = Math.min(PROGRAM.length, at + 24);
      setSource(PROGRAM.slice(0, at));
      if (at === PROGRAM.length) {
        clearInterval(timer.current);
        setStreaming(false);
      }
    }, 16);
  };
  useEffect(() => () => clearInterval(timer.current), []);

  return (
    <main className="mx-auto grid max-w-3xl gap-6 p-6">
      <header className="flex flex-wrap items-center gap-3 text-sm">
        <strong>GistUI + shadcn/ui</strong>
        <label className="flex items-center gap-2">
          <input type="checkbox" checked={shadcn} onChange={(e) => setShadcn(e.target.checked)} /> Render with shadcn/ui
        </label>
        <button type="button" className="underline" onClick={stream}>
          Stream again
        </button>
      </header>
      <GistUI library={shadcn ? shadcnUI : ui} tokens={shadcn ? shadcnTokens : undefined} source={source} streaming={streaming} onAction={(a) => setActions((xs) => [a, ...xs])} />
      {actions.length > 0 && <pre className="overflow-auto rounded-lg bg-muted p-3 text-xs">{actions.map((a) => JSON.stringify(a.type === "submit" ? { type: a.type, partial: a.partial, values: a.values } : a)).join("\n")}</pre>}
    </main>
  );
}
