// examples/solid/src/parity.tsx
/** Renderer parity page for `@gistui/solid` (see tests/visual/parity.spec.ts). */
import { GistUI } from "@gistui/solid";
import { onMount } from "solid-js";
import { render } from "solid-js/web";
// The playground's examples, demo tools and page setup, shared by every parity page.
import { demoTools, paritySetup } from "../../../apps/playground/src/parity-setup";

const { example, theme, stage, ready } = paritySetup();
render(() => {
  onMount(() => ready("solid"));
  return <GistUI source={example.source} theme={theme} tools={demoTools} />;
}, stage);

// apps/playground/src/parity.tsx
/**
 * Renderer parity page (used by tests/visual/parity.spec.ts): one example rendered by React
 * (`?r=react`) or by the vanilla renderer (`?r=vanilla`), with nothing else on the page.
 * Vue, Svelte and Solid have the same page in their example apps (`examples/*`).
 */
import { mount } from "@gistui/vanilla";
import { ui as domUi } from "@gistui/vanilla/ui";
import { GistUI } from "@gistui/react";
import { ui } from "@gistui/react/ui";
import { createRoot } from "react-dom/client";
import { demoTools, paritySetup } from "./parity-setup";

const { example, theme, stage, ready } = paritySetup();
if (new URLSearchParams(location.search).get("r") === "vanilla") {
  mount(stage, { library: domUi, source: example.source, theme, tools: demoTools });
  ready("vanilla");
} else {
  createRoot(stage).render(<GistUI library={ui} source={example.source} theme={theme} tools={demoTools} />);
  ready("react");
}
